module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/Hkl27CXZ1s6A9TVt8kN8id',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/1grtny.png',
    NEWSLETTER_JID: '120363421408345374@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐐𝐔𝐄𝐄𝐍 𝐋𝐈𝐓𝐇𝐔𝐋𝐈n𝚇 𝗠𝗗 MINI BOT 𝗩1',
    OWNER_NAME: 'ꪶ ᴋʟᴡ : 𝐎𝐋𝐃 𝐖𝐇𝐈𝐓𝐄 𝐃𝐑𝐀𝐆𝐎𝐍 ꫂ ᴰ ᵀ ᶻ',
    OWNER_NUMBER: '94776532488',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> 𝐐𝐔𝐄𝐄𝐍 𝐋𝐈𝐓𝐇𝐔𝐋𝐈 𝐌𝐃 𝚇 𝗠𝗗 𝗩1',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBrdrQDzgTKjwWJwn3A',
};
